const artists = [
  {
    rank: 1,
    name: 'Kaia Morreau',
    genre: 'Alt R&B',
    score: 97,
    signals: [
      { label: 'Monthly listeners', value: '+412%', period: '30d' },
      { label: 'TikTok sounds', value: '18.7K videos' },
      { label: 'Playlist adds', value: '63 this week' },
    ],
    chartBars: [15, 22, 28, 35, 42, 55, 68, 78, 85, 92, 97, 100],
    trend: 'up',
  },
  {
    rank: 2,
    name: 'DVNIEL',
    genre: 'Hyperpop',
    score: 94,
    signals: [
      { label: 'Monthly listeners', value: '+340%', period: '30d' },
      { label: 'TikTok sounds', value: '12.4K videos' },
      { label: 'Playlist adds', value: '47 this week' },
    ],
    chartBars: [10, 15, 20, 25, 35, 48, 58, 70, 80, 88, 94, 96],
    trend: 'up',
  },
  {
    rank: 3,
    name: 'Solène',
    genre: 'Dream Pop',
    score: 91,
    signals: [
      { label: 'Monthly listeners', value: '+287%', period: '30d' },
      { label: 'TikTok sounds', value: '8.2K videos' },
      { label: 'Playlist adds', value: '39 this week' },
    ],
    chartBars: [12, 18, 22, 30, 38, 45, 55, 62, 72, 80, 88, 91],
    trend: 'up',
  },
  {
    rank: 4,
    name: 'jnr bxndit',
    genre: 'UK Drill',
    score: 89,
    signals: [
      { label: 'Monthly listeners', value: '+256%', period: '30d' },
      { label: 'TikTok sounds', value: '6.9K videos' },
      { label: 'Playlist adds', value: '31 this week' },
    ],
    chartBars: [8, 12, 18, 25, 32, 40, 50, 60, 70, 78, 85, 89],
    trend: 'up',
  },
  {
    rank: 5,
    name: 'Aura Vega',
    genre: 'Latin Pop',
    score: 87,
    signals: [
      { label: 'Monthly listeners', value: '+231%', period: '30d' },
      { label: 'TikTok sounds', value: '5.4K videos' },
      { label: 'Playlist adds', value: '28 this week' },
    ],
    chartBars: [10, 14, 20, 28, 35, 42, 52, 58, 65, 74, 82, 87],
    trend: 'up',
  },
];

function ScoreBadge({ score }: { score: number }) {
  const color =
    score >= 95
      ? 'text-emerald-400 bg-emerald-400/10 border-emerald-400/20'
      : score >= 90
        ? 'text-brand-blue bg-brand-blue/10 border-brand-blue/20'
        : 'text-amber-400 bg-amber-400/10 border-amber-400/20';

  return (
    <span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-md text-sm font-bold border ${color}`}>
      {score}
    </span>
  );
}

function MiniChart({ bars }: { bars: number[] }) {
  const max = Math.max(...bars);
  return (
    <div className="mini-chart">
      {bars.map((val, i) => (
        <div
          key={i}
          className="bar"
          style={{ height: `${(val / max) * 100}%`, opacity: 0.4 + (i / bars.length) * 0.6 }}
        />
      ))}
    </div>
  );
}

export default function SampleReport() {
  return (
    <section className="section-padding bg-gradient-to-b from-brand-dark via-brand-darker to-brand-dark" id="report">
      <div className="container-tight">
        {/* Header */}
        <div className="text-center mb-16">
          <p className="text-brand-blue font-semibold text-sm uppercase tracking-wider mb-3">
            Sample Report
          </p>
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            See what the <span className="gradient-text-blue">Hot&nbsp;50</span> looks like
          </h2>
          <p className="text-brand-muted text-lg max-w-xl mx-auto">
            Every Monday, subscribers receive a ranked report of the 50 artists most likely to break out — with data-backed signals.
          </p>
        </div>

        {/* Report mock */}
        <div className="glass-card p-6 md:p-8 max-w-4xl mx-auto">
          {/* Report header */}
          <div className="flex items-center justify-between mb-6 pb-4 border-b border-brand-border">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <div className="w-2 h-2 rounded-full bg-brand-blue" />
                <span className="text-sm font-mono text-brand-muted">LABELINTEL HOT 50</span>
              </div>
              <p className="text-xs text-brand-muted">Week of March 24, 2026 · Generated by AI</p>
            </div>
            <span className="px-3 py-1 rounded-full bg-brand-green/10 border border-brand-green/20 text-brand-green text-xs font-medium">
              LIVE DATA
            </span>
          </div>

          {/* Artist cards */}
          <div className="space-y-3">
            {artists.map((artist) => (
              <div
                key={artist.rank}
                className="flex items-center gap-4 p-4 rounded-xl bg-brand-dark/50 border border-brand-border
                           hover:border-brand-blue/20 hover:bg-brand-card/50 transition-all group"
              >
                {/* Rank */}
                <div className="w-8 text-center">
                  <span className="text-lg font-bold text-brand-muted group-hover:text-white transition-colors">
                    {artist.rank}
                  </span>
                </div>

                {/* Artist info */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <h4 className="font-semibold truncate">{artist.name}</h4>
                    <span className="px-2 py-0.5 rounded text-xs font-medium bg-brand-blue/10 text-brand-blue-light border border-brand-blue/20">
                      {artist.genre}
                    </span>
                  </div>
                  <div className="flex flex-wrap gap-x-4 gap-y-1">
                    {artist.signals.map((signal) => (
                      <span key={signal.label} className="text-xs text-brand-muted">
                        {signal.label}:{' '}
                        <span className="text-brand-green font-medium">{signal.value}</span>
                        {signal.period && (
                          <span className="text-brand-muted/60"> ({signal.period})</span>
                        )}
                      </span>
                    ))}
                  </div>
                </div>

                {/* Mini chart */}
                <div className="hidden sm:block">
                  <MiniChart bars={artist.chartBars} />
                </div>

                {/* Score */}
                <div className="flex-shrink-0">
                  <ScoreBadge score={artist.score} />
                </div>
              </div>
            ))}
          </div>

          {/* Footer hint */}
          <div className="mt-6 pt-4 border-t border-brand-border text-center">
            <p className="text-sm text-brand-muted">
              Showing 5 of 50 artists ·{' '}
              <span
                className="text-brand-blue cursor-pointer hover:underline"
                onClick={() => document.getElementById('waitlist')?.scrollIntoView({ behavior: 'smooth' })}
              >
                Get the full report →
              </span>
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
